// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.Codesi.Encuestas.Persistencia.Core.Models;

public partial class Encuesta
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Nombre { get; set; }

    public bool Activo { get; set; }

    [Required]
    public string Periodo { get; set; }

    [Required]
    public string Dependencia { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaInicio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaFin { get; set; }

    [Required]
    [Column("valoresEncuesta")]
    public string ValoresEncuesta { get; set; }

    [InverseProperty("IdEncuestaNavigation")]
    public virtual ICollection<Resultado> Resultado { get; set; } = new List<Resultado>();
}