// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Unach.Codesi.Encuestas.Persistencia.Core.Models;

public partial class EncuestasContext : DbContext
{
    public EncuestasContext(DbContextOptions<EncuestasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Encuesta> Encuesta { get; set; }

    public virtual DbSet<Resultado> Resultado { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Encuesta>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Encuesta__3214EC078883F347");
        });

        modelBuilder.Entity<Resultado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Resultad__3214EC075A474D1A");

            entity.HasOne(d => d.IdEncuestaNavigation).WithMany(p => p.Resultado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Resultado__IdEnc__60A75C0F");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Resultado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Resultado__IdUsu__619B8048");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuario__3214EC079D1302B3");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}