// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.Codesi.Encuestas.Persistencia.Core.Models;

public partial class Resultado
{
    [Key]
    public int Id { get; set; }

    public int IdEncuesta { get; set; }

    public int IdUsuario { get; set; }

    [Required]
    [Column("valorResultado")]
    public string ValorResultado { get; set; }

    [ForeignKey("IdEncuesta")]
    [InverseProperty("Resultado")]
    public virtual Encuesta IdEncuestaNavigation { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("Resultado")]
    public virtual Usuario IdUsuarioNavigation { get; set; }
}