// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Unach.Codesi.Encuestas.Persistencia.Core.Models;

public partial class Usuario
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Nombre { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<Resultado> Resultado { get; set; } = new List<Resultado>();
}